magento2_version: ''

nginx_image: 'docker.io/markoshust/magento-nginx'
nginx_tag: '1.24-0'

mariadb_image: 'docker.io/mariadb'
mariadb_tag: '11.4'

opensearch_image: 'docker.io/markoshust/magento-opensearch'
opensearch_tag: '2.5-1'

magento2_image: ''
magento2_tag: ''

magento2_url: ''

github_api_token: ''
gitlab_api_token: ''

hipay_api_user_test: ''
hipay_api_password_test: ''
hipay_secret_passphrase_test: ''
hipay_tokenjs_username_test: ''
hipay_tokenjs_publickey_test: ''
hipay_applepay_username_test: ''
hipay_applepay_password_test: ''
hipay_applepay_secret_passphrase_test: ''
hipay_applepay_tokenjs_username_test: ''
hipay_applepay_tokenjs_publickey_test: ''

pi_data_url: ''
