apiVersion: v1
kind: Service
metadata:
  name: magento2-mariadb-{{ .Release.Name }}
  labels:
    app: magento2-{{ .Release.Name }}
    cd-hipay: cron-delete
spec:
  ports:
    - port: 3306
  selector:
    app: magento2-{{ .Release.Name }}
    tier: mariadb-{{ .Release.Name }}
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim-{{ .Release.Name }}
  labels:
    app: magento2-{{ .Release.Name }}
    cd-hipay: cron-delete
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento2-mariadb-{{ .Release.Name }}
  labels:
    app: magento2-{{ .Release.Name }}
    cd-hipay: cron-delete
spec:
  selector:
    matchLabels:
      app: magento2-{{ .Release.Name }}
      tier: mariadb-{{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento2-{{ .Release.Name }}
        tier: mariadb-{{ .Release.Name }}
        cd-hipay: cron-delete
    spec:
      containers:
      - image: {{ .Values.mariadb_image }}:{{ .Values.mariadb_tag }}
        name: mariadb-{{ .Release.Name }}
        args:
          - "--max_allowed_packet=64M"
          - "--optimizer_use_condition_selectivity=1"
          - "--optimizer_switch=rowid_filter=off"
          - "--log_bin_trust_function_creators=1"
        resources:
          requests:
            memory: "2.5G"
            cpu: "1000m"
        envFrom:
          - configMapRef:
              name: magento2-configmap-{{ .Release.Name }}
          - secretRef:
              name: magento2-secrets-{{ .Release.Name }}
        ports:
          - containerPort: 3306
            name: mariadb
        volumeMounts:
          - name: mariadb-persistent-storage-{{ .Release.Name }}
            mountPath: /var/lib/mysql
            subPath: mariadb
      volumes:
        - name: mariadb-persistent-storage-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: mariadb-pv-claim-{{ .Release.Name }}
